src/Entity/Billet.php
<?php

namespace App\Entity;

use App\Repository\BilletRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

#[ORM\Entity(repositoryClass: BilletRepository::class)]
#[Vich\Uploadable]
class Billet
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $pays = null;

    #[ORM\ManyToOne(inversedBy: 'billets', cascade: ['persist'])]
    #[ORM\JoinColumn(nullable: false)]
    private ?Album $album = null;

    #[ORM\Column(length: 255)]
    private ?string $valeur = null;

    #[ORM\Column(length: 255)]
    private ?string $DateApparition = null;

    /**
     * @var Collection<int, Exposition>
     */
    #[ORM\ManyToMany(targetEntity: Exposition::class, mappedBy: 'billets')]
    private Collection $expositions;

    #[Vich\UploadableField(mapping: 'billets', fileNameProperty: 'imageName', size: 'imageSize')]
    private ?File $imageFile = null;

    #[ORM\Column(nullable: true)]
    private ?string $imageName = null;

    #[ORM\Column(nullable: true)]
    private ?int $imageSize = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updatedAt = null;

      //...
    /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $imageFile
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageName(?string $imageName): void
    {
        $this->imageName = $imageName;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function setImageSize(?int $imageSize): void
    {
        $this->imageSize = $imageSize;
    }

    public function getImageSize(): ?int
    {
        return $this->imageSize;
    }
    
    public function __construct()
    {
        $this->expositions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPays(): ?string
    {
        return $this->pays;
    }

    public function setPays(string $pays): static
    {
        $this->pays = $pays;

        return $this;
    }

    public function getAlbum(): ?Album
    {
        return $this->album;
    }

    public function setAlbum(?Album $album): static
    {
        $this->album = $album;

        return $this;
    }

    public function getValeur(): ?string
    {
        return $this->valeur;
    }

    public function setValeur(string $valeur): static
    {
        $this->valeur = $valeur;

        return $this;
    }

    public function getDateApparition(): ?string
    {
        return $this->DateApparition;
    }

    public function setDateApparition(string $DateApparition): static
    {
        $this->DateApparition = $DateApparition;

        return $this;
    }

    /**
     * @return Collection<int, Exposition>
     */
    public function getExpositions(): Collection
    {
        return $this->expositions;
    }

    public function addExposition(Exposition $exposition): static
    {
        if (!$this->expositions->contains($exposition)) {
            $this->expositions->add($exposition);
            $exposition->addBillet($this);
        }

        return $this;
    }

    public function removeExposition(Exposition $exposition): static
    {
        if ($this->expositions->removeElement($exposition)) {
            $exposition->removeBillet($this);
        }

        return $this;
    }

    
    public function __toString(): string
    {
        return sprintf('%s - %s', $this->pays, $this->valeur);
    }
}

src/Entity/Exposition.php
<?php

namespace App\Entity;

use App\Repository\ExpositionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ExpositionRepository::class)]
class Exposition
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $description = null;

    #[ORM\Column]
    private ?bool $publiee = null;

    #[ORM\ManyToOne(targetEntity: Member::class, inversedBy: 'expositions')]
    private ?Member $member = null;

    /**
     * @var Collection<int, Billet>
     */
    #[ORM\ManyToMany(targetEntity: Billet::class, inversedBy: 'expositions')]
    private Collection $billets;

    public function __construct()
    {
        $this->billets = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function isPubliee(): ?bool
    {
        return $this->publiee;
    }

    public function setPubliee(bool $publiee): static
    {
        $this->publiee = $publiee;

        return $this;
    }

    public function getMember(): ?Member
    {
        return $this->member;
    }

    public function setMember(?Member $member): static
    {
        $this->member = $member;

        return $this;
    }

    /**
     * @return Collection<int, Billet>
     */
    public function getBillets(): Collection
    {
        return $this->billets;
    }

    public function addBillet(Billet $billet): static
    {
        if (!$this->billets->contains($billet)) {
            $this->billets->add($billet);
            $billet->addExposition($this);
        }

        return $this;
    }

    public function removeBillet(Billet $billet): static
    {
        if ($this->billets->removeElement($billet)) {
            $billet->removeExposition($this); // Maintain bidirectional relationship
        }
        return $this;
    }
}

src/Form/ExpositionType.php
<?php

namespace App\Form;

use App\Entity\Billet;
use App\Entity\Exposition;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use App\Repository\BilletRepository;

class ExpositionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $exposition = $options['data'] ?? null;
        $member =  $exposition->getMember();

        $builder
            ->add('description')
            ->add('publiee')
            ->add('billets', null, [
                'multiple' => true,
                'expanded' => true,
                'by_reference' => false,
                // Limit billet choices to those in the member's album
                'query_builder' => function (BilletRepository $repository) use ($member) {
                    return $repository->createQueryBuilder('o')
                        ->leftJoin('o.album', 'i')
                        ->leftJoin('i.member', 'm')
                        ->where('m.id = :memberId')
                        ->setParameter('memberId',  $member->getId() );
                },
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Exposition::class,
        ]);
    }
}

src/Controller/ExpositionController.php
<?php

namespace App\Controller;

use App\Entity\Exposition;
use App\Entity\Billet;
use App\Form\ExpositionType;
use App\Entity\Member;
use App\Repository\ExpositionRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bridge\Doctrine\Attribute\MapEntity;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[Route('/exposition')]
final class ExpositionController extends AbstractController
{

    #[Route('/{exposition_id}/billet/{billet_id}', name: 'app_exposition_billet_show', methods: ['GET'])]
    #[IsGranted('ROLE_USER')] 
    public function billetShow(
        #[MapEntity(id: 'exposition_id')] Exposition $exposition,
        #[MapEntity(id: 'billet_id')] Billet $billet
    ): Response {
        if (!$exposition->getBillets()->contains($billet)) {
            throw $this->createNotFoundException("Couldn't find such a billet in this exposition!");
        }
    
        $hasAccess = false;
        if ($this->isGranted('ROLE_ADMIN') || $exposition->isPubliee()) {
            $hasAccess = true;
        } else {
            $member = $this->getUser();
            if ($member && ($member === $exposition->getMember())) {
                $hasAccess = true;
            }
        }
    
        if (!$hasAccess) {
            throw $this->createAccessDeniedException("You cannot access the requested resource!");
        }
    
        return $this->render('exposition/billetshow.html.twig', [
            'billet' => $billet,
            'exposition' => $exposition
        ]);
    }
    #[Route('/', name: 'app_exposition_index', methods: ['GET'])]
    public function index(ExpositionRepository $expositionRepository): Response
    {
        $member = $this->getUser();
        $publicExpositions = $expositionRepository->findBy(['publiee' => true]);

        $privateExpositions = [];
        if ($member) {
            $privateExpositions = $expositionRepository->findBy([
                'publiee' => false,
                'member' => $member,
            ]);
        }

        return $this->render('exposition/index.html.twig', [
            'public_expositions' => $publicExpositions,
            'private_expositions' => $privateExpositions,
        ]);
    }
    // #[Route('/new', name: 'app_exposition_new', methods: ['GET', 'POST'])]
    // public function new(Request $request, EntityManagerInterface $entityManager): Response
    // {
    //     $exposition = new Exposition();
    //     $form = $this->createForm(ExpositionType::class, $exposition);
    //     $form->handleRequest($request);

    //     if ($form->isSubmitted() && $form->isValid()) {
    //         $entityManager->persist($exposition);
    //         $entityManager->flush();

    //         return $this->redirectToRoute('app_exposition_index', [], Response::HTTP_SEE_OTHER);
    //     }

    //     return $this->render('exposition/new.html.twig', [
    //         'exposition' => $exposition,
    //         'form' => $form,
    //     ]);
    // }

    #[IsGranted('ROLE_USER')] 
    #[Route('/new/{memberId}', name: 'app_exposition_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager, #[MapEntity(id: 'memberId')] Member $member): Response
    {
        // Create a new Exposition and associate it with the given Member
        $exposition = new Exposition();
        $exposition->setMember($member);

        // Create and handle the form
        $form = $this->createForm(ExpositionType::class, $exposition);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($exposition);
            $entityManager->flush();

            // Redirect to the member's profile page after creation
            return $this->redirectToRoute('app_member_show', [
                'id' => $member->getId(),
            ], Response::HTTP_SEE_OTHER);
        }

        return $this->render('exposition/new.html.twig', [
            'exposition' => $exposition,
            'form' => $form,
            'member' => $member,
        ]);
    }

    #[Route('/{id}', name: 'app_exposition_show', methods: ['GET'])]
    public function show(Exposition $exposition): Response
    {
            $hasAccess = false;
            if($this->isGranted('ROLE_ADMIN') || $exposition->isPubliee()) {
                    $hasAccess = true;
            }
            else {
                    $member = $this->getUser();
                    if ( $member &&  ($member == $exposition->getMember()) ) {
                        $hasAccess = true;
                    }
            }
            if(! $hasAccess) {
                    throw $this->createAccessDeniedException("You cannot access the requested resource!");
            }
            return $this->render('exposition/show.html.twig', [
                    'exposition' => $exposition,
            ]);
    }
    

    #[Route('/{id}/edit', name: 'app_exposition_edit', methods: ['GET', 'POST'])]
    #[IsGranted('ROLE_USER')] 
    public function edit(Request $request, Exposition $exposition, EntityManagerInterface $entityManager): Response
    {
        if (!$this->isGranted('ROLE_ADMIN') && $this->getUser() !== $exposition->getMember()) {
            throw $this->createAccessDeniedException("You do not have permission to edit this exposition.");
        }
    
        $form = $this->createForm(ExpositionType::class, $exposition);
        $form->handleRequest($request);
    
        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();
    
            return $this->redirectToRoute('app_exposition_show', [
                'id' => $exposition->getId(),
            ], Response::HTTP_SEE_OTHER);
        }
    
        return $this->render('exposition/edit.html.twig', [
            'exposition' => $exposition,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_exposition_delete', methods: ['POST'])]
    #[IsGranted('ROLE_USER')] 
    public function delete(Request $request, Exposition $exposition, EntityManagerInterface $entityManager): Response
    {
        $memberId = $exposition->getMember()->getId();
        $hasAccess = false;
    
        // Check if the user has access to delete the exposition
        if ($this->isGranted('ROLE_ADMIN') || $this->getUser() === $exposition->getMember()) {
            $hasAccess = true;
        }
    
        if (!$hasAccess) {
            throw $this->createAccessDeniedException("You cannot delete this exposition!");
        }
    
        // Check the CSRF token for security
        if ($this->isCsrfTokenValid('delete' . $exposition->getId(), $request->get('_token'))) {
            $entityManager->remove($exposition);
            $entityManager->flush();
        }
    
        // Redirect to the member's profile page after deletion
        return $this->redirectToRoute('app_member_show', [
            'id' => $memberId,
        ], Response::HTTP_SEE_OTHER);
    }
    
}

templates/exposition/_delete_form.html.twig
<form method="post" action="{{ path('app_exposition_delete', {'id': exposition.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ exposition.id) }}">
    <button class="btn btn-primary">Delete</button>
</form>

templates/exposition/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/exposition/billetshow.html.twig
{% extends 'base.html.twig' %}

{% block title %}Billet n°{{ billet.id }}{% endblock %}

{% block body %}
    <h1>Billet Details</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>ID</th>
                <td>{{ billet.id }}</td>
            </tr>
            <tr>
                <th>Pays</th>
                <td>{{ billet.pays }}</td>
            </tr>
            <tr>
                <th>Valeur</th>
                <td>{{ billet.valeur }}</td>
            </tr>
            <tr>
                <th>Date d'apparition</th>
                <td>{{ billet.dateApparition }}</td>
            </tr>
            <tr>
                <th>Expositions</th>
                <td>
                    <ul>
                    {% for exposition in billet.expositions %}
                        <li>
                            <a href="{{ path('app_exposition_show', { 'id': exposition.id }) }}">
                                {{ exposition.description }}
                            </a>
                        </li>
                    {% else %}
                        <li>Aucune exposition associée à ce billet.</li>
                    {% endfor %}
                    </ul>
                </td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_exposition_show', { 'id': exposition.id }) }}">Retour à l'exposition</a>
{% endblock %}

templates/exposition/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Exposition{% endblock %}

{% block body %}
    <h1>Edit Exposition</h1>

    {{ include('exposition/_form.html.twig', {'button_label': 'Update'}) }}

    <a class="btn btn-primary" href="{{ path('app_exposition_index') }}">back to list</a>

    {{ include('exposition/_delete_form.html.twig') }}
{% endblock %}

templates/exposition/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Expositions{% endblock %}

{% block body %}
<div class="container mt-5">
    <h1 class="mb-4">Expositions</h1>

    <h2 class="text-primary">Expositions Publiques</h2>
    <table class="table table-striped table-hover">
        <thead class="table-dark">
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Description</th>
                <th scope="col">Publiée</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for exposition in public_expositions %}
            <tr>
                <td>{{ exposition.id }}</td>
                <td>{{ exposition.description }}</td>
                <td>{{ exposition.publiee ? 'Oui' : 'Non' }}</td>
                <td>
                    <a href="{{ path('app_exposition_show', {'id': exposition.id}) }}" class="btn btn-outline-primary btn-sm">
                        Afficher
                    </a>
                    {% if is_granted('ROLE_ADMIN') or (app.user is not null and exposition.member is not null and exposition.member.id == app.user.id) %}
                        <a href="{{ path('app_exposition_edit', {'id': exposition.id}) }}" class="btn btn-outline-secondary btn-sm">
                            Modifier
                        </a>
                    {% endif %}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4" class="text-center">Aucune exposition publique trouvée.</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {% if private_expositions is not empty %}
        <h2 class="text-success">Vos Expositions Privées</h2>
        <table class="table table-striped table-hover">
            <thead class="table-dark">
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Description</th>
                    <th scope="col">Publiée</th>
                    <th scope="col">Actions</th>
                </tr>
            </thead>
            <tbody>
            {% for exposition in private_expositions %}
                <tr>
                    <td>{{ exposition.id }}</td>
                    <td>{{ exposition.description }}</td>
                    <td>{{ exposition.publiee ? 'Oui' : 'Non' }}</td>
                    <td>
                        <a href="{{ path('app_exposition_show', {'id': exposition.id}) }}" class="btn btn-outline-primary btn-sm">
                            Afficher
                        </a>
                        {% if app.user is not null and exposition.member is not null and exposition.member.id == app.user.id %}
                            <a href="{{ path('app_exposition_edit', {'id': exposition.id}) }}" class="btn btn-outline-secondary btn-sm">
                                Modifier
                            </a>
                        {% endif %}
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="4" class="text-center">Aucune exposition privée trouvée.</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% endif %}
</div>
{% endblock %}

templates/exposition/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Exposition{% endblock %}

{% block body %}
    <h1>Create new Exposition</h1>

    {{ include('exposition/_form.html.twig') }}

    <a href="{{ path('app_exposition_index') }}">back to list</a>
{% endblock %}

templates/exposition/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Exposition n°{{ exposition.id }}{% endblock %}

{% block body %}
<div class="container mt-5">
    <h1 class="mb-4">Détails de l'Exposition</h1>

    <table class="table table-bordered table-hover">
        <tbody>
            <tr>
                <th scope="row">ID</th>
                <td>{{ exposition.id }}</td>
            </tr>
            <tr>
                <th scope="row">Description</th>
                <td>{{ exposition.description }}</td>
            </tr>
            <tr>
                <th scope="row">Publiée</th>
                <td>{{ exposition.publiee ? 'Oui' : 'Non' }}</td>
            </tr>
            <tr>
                <th scope="row">Billets de l'exposition</th>
                <td>
                    <ul class="list-group">
                    {% for billet in exposition.billets %}
                        <li class="list-group-item d-flex align-items-center">
                            {% if billet.imageName %}
                                <img src="{{ vich_uploader_asset(billet, 'imageFile') }}" alt="{{ billet.pays }}" class="img-thumbnail me-3" style="width: 100px; height: auto;">
                            {% else %}
                                <div class="text-muted me-3" style="width: 100px; height: auto; text-align: center; line-height: 100px; border: 1px dashed #ccc;">
                                    Aucune image
                                </div>
                            {% endif %}
                            <a href="{{ path('app_exposition_billet_show', {
                                'exposition_id': exposition.id,
                                'billet_id': billet.id
                            }) }}" class="text-decoration-none">
                                {{ billet.pays }} - {{ billet.valeur }}
                            </a>
                        </li>
                    {% else %}
                        <li class="list-group-item text-muted">Aucun billet dans cette exposition.</li>
                    {% endfor %}
                    </ul>
                </td>
            </tr>
        </tbody>
    </table>

    <div class="d-flex mt-4">
        <a href="{{ path('app_exposition_index') }}" class="btn btn-secondary me-2">Retour à la liste</a>
        <a href="{{ path('app_exposition_edit', {'id': exposition.id}) }}" class="btn btn-primary">Editer</a>
    </div>

    {{ include('exposition/_delete_form.html.twig') }}
</div>
{% endblock %}